refactor: use deno & emit and remove vite
yuki-93/6-2-1-rules pull request #7
Opened 2023-09-03 15:31 UTC by EdJoPaTo

Move some files, everything in public is now the public folder to be deployed.
Also run `demo fmt` to use a common code style.

2023-09-03 15:42 UTC, yuki-93 commented
What are denos presets for ts? I want to have "noExplicitAny" and "strict" to enforce types and avoid "anys". Is this the case?

Can you explain me, how the automation with the release will work or what I have to to? 

Thanks for your work so far. 

Also will test this on my machine later, so takes some time to apply this PR.

2023-09-03 16:02 UTC, EdJoPaTo commented
> What are denos presets for ts? I want to have "noExplicitAny" and "strict" to enforce types and avoid "anys". Is this the case?

Both you mentioned are [enabled by default](https://deno.land/manual/advanced/typescript/configuration).

[Personally I consider to enable even more tsconfig rules to be even more strict](https://github.com/EdJoPaTo/deno-runtime-template/blob/6dde7104c24d7af5cf76b029340a21814509d343/deno.jsonc#L7-L16) but this would create more churn in this PQ which is why I didn't.

> Can you explain me, how the automation with the release will work or what I have to to?

On every commit the CI is run to do stuff like `demo lint`, `deno check *.ts` and `deno task bundle`. The last one is added as a build artefact so you can simply take it from every run and deploy the given build with a static web server.

On tags starting with v a GitHub release is generated and the artefact added to it.

2023-09-03 16:05 UTC, yuki-93 commented
Feel free to create an issue for the following ts config work ☺️

2023-09-04 19:44 UTC, yuki-93 commented
> Feel free to create an issue for the following ts config work ☺️

Created #8 for the following ts rules

2023-09-05 08:16 UTC, yuki-93 requested changes

2023-09-05 08:20 UTC, EdJoPaTo commented on deno.jsonc
> +    "bundle": "deno run --allow-env --allow-read --allow-write=public/main.js --allow-net=deno.land bundle.ts"
What do you want as "dev-mode"?

2023-09-05 08:24 UTC, yuki-93 commented on deno.jsonc
> +    "bundle": "deno run --allow-env --allow-read --allow-write=public/main.js --allow-net=deno.land bundle.ts"
Some kind of dev-server for local development with hot module reloading :) 
So start a dev command in the sh and let it run, changes are automatically applied.

2023-09-05 08:28 UTC, EdJoPaTo commented on bundle.ts
> +await Deno.writeTextFile("public/main.js", code);
As this is static content a server like nginx will generate [ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) to handle reduce traffic.
Changing the filename on different builds requires the HTML to have a short caching time while the JS/CSS would need high caching times to be useful.
Currently the production web-server uses only ETags and no caching time at all making this approach basically useless. Personally I think it is overkill for such a small project which is rarely updated anyway.

2023-09-05 08:28 UTC, EdJoPaTo commented on main.ts
> +async function prepareData(): Promise<Array<Array<string>>> {
Personally I think a function stated as a function is way more readable but its your project.

2023-09-05 08:35 UTC, yuki-93 requested changes
Looks fine, waiting for dev mode to be added.

2023-09-05 08:38 UTC, EdJoPaTo commented on deno.jsonc
> +    "bundle": "deno run --allow-env --allow-read --allow-write=public/main.js --allow-net=deno.land bundle.ts"
599035b3fc3a88952aeaf584ac63fd0cc6c6e8c8

2023-09-05 09:03 UTC, yuki-93 reviewed
Thanks🤗. Will test this later on, but Code looks fine so far.

2023-09-06 16:03 UTC, yuki-93 commented
deno seem to be not the right tool for this. So closing this PR. But thanks for your work and contribution.

2023-09-06 16:03 UTC, closed without merging